name: Publish Website to CPanel
on:
  push:
    branches:
      - production
jobs:
  Cypress-Tests-And-Deploy-Cpanel:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
          fetch-depth: 2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: gatsby develop
          wait-on: 'http://localhost:8000'
          config: baseUrl=http://localhost:8000

      - name: Build Project
        run: |
          npm install
          npm run build --if-present

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public
