name: Publish Website to CPanel
on:
  push:
    branches:
      - production
jobs:
  Cypress-Tests-And-Deploy-Cpanel:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2.4.0
        with:
          start: npm run start
          wait-on: "http://localhost:8000"
          env: APP_URL=http://localhost:8000

      - name: Build Project
        run: npm run build --if-present

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
